[package]
name = "capsule-cli"
version = "0.1.0"
edition = "2024"


[dependencies]
clap = { version = "4.5.53", features = ["derive"] }
capsule-core = { path = "../capsule-core" }
tokio = { version = "1.48.0", features = ["rt", "rt-multi-thread", "macros"] }
serde_json = "1"
indicatif = "0.17"


