[package]
name = "capsule-core"
version = "0.1.0"
edition = "2024"

[dependencies]
rusqlite = "0.37.0"
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.145"
uuid = { version = "1.19.0", features = ["v4", "serde"] }
