name: CI

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  rust-fmt:
    name: Rust Format Check
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt, clippy

      - name: Check formatting (capsule-cli)
        working-directory: crates/capsule-cli
        run: cargo fmt --all -- --check

      - name: Check formatting (capsule-core)
        working-directory: crates/capsule-core
        run: cargo fmt --all -- --check

      - name: Run clippy (capsule-cli)
        working-directory: crates/capsule-cli
        run: cargo clippy --all-targets --all-features -- -D warnings

      - name: Run clippy (capsule-core)
        working-directory: crates/capsule-core
        run: cargo clippy --all-targets --all-features -- -D warnings

  rust-core-tests:
    name: Rust Core Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Run cargo test in crates/capsule-core
        working-directory: crates/capsule-core
        run: cargo test --all --verbose

      - name: Run cargo test in crates/capsule-cli
        working-directory: crates/capsule-cli
        run: cargo test --all --verbose
